events {}

http {
    # Esto le dice a Nginx cómo traducir nombres (como google.com) a IPs
    #resolver 8.8.8.8;
    
    # Este bloque atrapa cualquier petición con un Host desconocido
    server {
        listen 80 default_server;
        listen 443 ssl default_server;
        server_name _;
        return 444; # Simplemente cierra la conexión
    }
    
    server {
        listen 80;

        location /api-a {
            # Importante: A veces ayuda poner la URL en una variable
            # o asegurarse de que termine en /
            proxy_pass https://jsonplaceholder.typicode.com/;
            # Estas 3 líneas son el "combo" para que las APIs externas no te reboten
            proxy_set_header Host jsonplaceholder.typicode.com; # Le dice a la API: "Sé que te estoy llamando a ti". Muchos servidores (como los de Heroku o Amazon donde viven estas APIs) alojan miles de sitios en una misma IP. Si no les dices el nombre del Host, el servidor no sabe a cuál de esos miles de sitios quieres entrar.
            proxy_ssl_server_name on; # Activa algo llamado SNI (Server Name Indication). Cuando usas HTTPS, se establece una conexión segura antes de enviar los datos. Este comando le avisa al servidor externo qué certificado de seguridad debe mostrarte para que la conexión no falle al inicio. Sin esto, el "apretón de manos" de seguridad se rompe. --- Cuando usas HTTPS, lo primero que ocurre es el "apretón de manos" (Handshake TLS). En este paso, el servidor debe enviarte su certificado (.pem o .crt) para demostrar quién es. 
            proxy_set_header User-Agent Docker-Proxy-Santi; # Identifica quién está haciendo la petición (un navegador, un script, o en este caso, tu proxy). PIs como la de GitHub bloquean cualquier petición que no tenga un User-Agent. Lo hacen para evitar ataques de bots automáticos. Al ponerle un nombre, la API se queda tranquila porque sabe "quién" le habla.
        }

        location /api-b {
            proxy_pass https://api.github.com/;
            proxy_set_header Host api.github.com;
            proxy_set_header User-Agent Peticion-Docker; # GitHub a veces bloquea si no hay User-Agent
        }
    }

    # Servidor 1: El oficial
    server {
        listen 443 ssl;
        server_name localhost;
        ssl_certificate     /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        location / {
            return 200 "Respuesta desde LOCALHOST\n";
        }
    }

    # Servidor 2: El "intruso"
    server {
        listen 443 ssl;
        server_name santiproject.test;
        ssl_certificate     /etc/nginx/certs/santi.crt;
        ssl_certificate_key /etc/nginx/certs/santi.key;

        location / {
            return 200 "Respuesta desde SANTIPROJECT.TEST\n";
        }
    }
}